FROM iainmackie/galago-base-image:v3

MAINTAINER iain mackie

CMD bash ./core/target/appassembler/bin/galago batch-search \
	--defaultTextPart=postings.krovetz \
	--b=${B} \
	--k=${K} \
	--requested=${HITS} \
	--index=${INDEX} \ 
	${CONFIG} > ${RUN}

